### PR TITLE
feat: top row graph + scoped style for all graphs

### PR DESCRIPTION
**Pull request by fquellec**
- Added a new chart for top-k bar charts to replace the old vega one. You can test it on the Twitter experience (top advertiser) : 
image
- Fixed several issues we had with overlapping styles between graphics using <style scoped>, this introduced a lot of problems with tooltips but they should all be fixed with this PR. Note that for style inside SVG content we need to prefix them with ```::v-deep``` otherwise they are not applied when used with <style scoped>.

### CODE REVIEW

**Review by ffsinger — APPROVED** [review]
Cool !

It's not very clear what the "average" aggregation does. Maybe change the x axis to "Count / day" in this case, or add a small explanation.

Can you reuse this graph for the facebook experience ? It's still using vega

**Comment by fquellec** [comment]
- I forgot to mention that this issue is related to #405.
- For the "average" aggregation, it doesn't make much sense anyway, I wanted to remove it but I need @foucault-dumas to confirm that it's ok to remove it? 
- For the Facebook experiment, I'll change the graph! Thanks for your review @ffsinger

**Comment by ffsinger** [comment]
It's also related to #335 (I didn't check if it was fixed though)

> For the "average" aggregation, it doesn't make much sense anyway, I wanted to remove it

I agree

**Comment by fquellec** [comment]
Yes it fixes #335 too, need to double check though

**Review by streitlua — CHANGES_REQUESTED** [review]
The graph looks good for me and indeed seems to fix #335, but the graph is a bit too large for my screen (it doesn't fit vertically), is there any way to make it smaller or adaptive?

**Comment by fquellec** [comment]
I pushed your recommendations, could you merge and close the PR @streitlua if you agree with the changes?

**Review by streitlua — APPROVED** [review]
That's better! I would decrease the font size of the x axis a bit but that's just my personal taste. I will merge it like this.

**Comment by foucault-dumas** [comment]
Thanks guys for all this.
I don't manage to see these changes on test.hestialabs.org nor on experiences.hestialabs.org 🤔

**Pull request merged**
