### PR TITLE
refactor: remove power view

### LINKED ISSUE #314: Remove the power experience
It's no longer used, and broken. 

Remove anything that depends on $store.state.power being true

### PR DESCRIPTION
**Pull request by streitlua**
Will close #314

### CODE REVIEW

**Review by ffsinger — APPROVED** [review]
Nice

I removed some obsolete stuff. Should we also delete `ModeSwitch.vue` and the `power` property in the Vuex store ?

**Comment by streitlua** [comment]
> Should we also delete `ModeSwitch.vue` and the `power` property in the Vuex store ?

Sounds good, can you take care of it?

**Comment by streitlua** [comment]
@ffsinger I merged `TheDataExperience` and `TheDataExperienceDefault`, can you check that everything works for you?

**Review by ffsinger — APPROVED** [review]
Very good

**Pull request merged**
