### PR TITLE
feat: add d3 TimeSeries component

### PR DESCRIPTION
**Pull request by fquellec**
Generic component to display time series, with customizable props accessible from the manifest thanks to Florian. 
lineplot

### CODE REVIEW

**Comment by fquellec** [comment]
Note that I replaced all line graphs of Tinder by this one

**Comment by ffsinger** [comment]
Screenshot_20211202_154847

On my browser the lines are kinda random, some appear and others don't, I don't know why. It changes with the zoom level

**Comment by streitlua** [comment]
> Screenshot_20211202_154847
> 
> On my browser the horizontal lines are kinda random, some appear and others don't, I don't know why. It changes with the zoom level

I encountered the same issue for one graph:
image

**Comment by streitlua** [comment]
The graphs look very nice though!

**Review by streitlua — APPROVED** [review]
Looks nice now!

**Pull request merged**
