### PR TITLE
fix: UI refactoring

### PR DESCRIPTION
**Pull request by fquellec**
This PR is related to #511 and apply the following changes: 
- make the whole experience page as tabs
- remove the shadow effect from the sub-experience cards
- display the newsletter as a disposable alert (and in the footer)
- make the share button at a fixed position. 
- Add title experiences in the app top bar

Demo: 
image

A lot can be done to improve the UI/UX, this is just a first step.
Now that the size of the sub-experience containers has changed, we need to improve the rendering of each sub-experience, but this could be done in separate issues.

### CODE REVIEW

**Comment by ffsinger** [comment]
The first part of the message on the alert should also be adaptive, because it's only The Eyeballs that is about the attention economy

Screenshot_20220121_154521

And personally I think that having the alert show up every time you refresh the page is a bit annoying, maybe we could keep the state in a cookie / localstorage, and show it back only once per day or something

**Comment by fquellec** [comment]
> and show it back only once per day or something

I agree !

**Review by ffsinger — APPROVED** [review]

**Comment by valentinoli** [comment]
Only problem with adding more things to the app bar is it doesn't take into account smaller screen sizes, on which I do not know how much emphasis we are putting... How important is it that the app looks good on mobile? For most apps, the importance is high.

image

**Comment by alexbfree** [comment]
> And personally I think that having the alert show up every time you refresh the page is a bit annoying, maybe we could keep the state in a cookie / localstorage, and show it back only once per day or something

I agree, we probably don't even want it at all for Digipower, certainly not once a day.

**Comment by ffsinger** [comment]
This could be configured by adding a parameter in https://github.com/hestiaAI/hestialabs-experiences/blob/master/config/digipower.json, so that we don't show it on digipower

**Pull request merged**
