### PR TITLE
fix: #218 and various

### LINKED ISSUE #218: All experiences are accessible through URL
Example: https://experiences.hestialabs.org/twitter-advertisers should not exist on this deployement. Is there a way to take them out of the build ?

We can also access "unavailable" experiences such as https://experiences.hestialabs.org/apple.

### PR DESCRIPTION
**Pull request by valentinoli**
* fixed #218, added a navigation guard middleware to `pages/_key.vue`
* moved `enabledExperiences`/`disabledExperiences` to the Vuex store
* improved newsletter code, better to keep code in `<script>` and `<template>` as clean as possible
* changed config loading to load the config in `manifests/index.js`
* added experience filter in `manifests/index.js` based on the config

### CODE REVIEW

**Review by ffsinger — APPROVED** [review]
Good !

**Comment by ffsinger** [comment]
Actually, I just pushed a small change: greyed out experiences now also return 404 because they're not supposed to be available

**Comment by valentinoli** [comment]
Ah didn't think of that! Thanks

**Comment by valentinoli** [comment]
better to do

```js
!store.getters.enabledExperiences.find(x => x.key === params.key)
```

**Comment by valentinoli** [comment]
When this is ready I need to merge it into `refactor/components` branch before organizing components into directories

**Comment by ffsinger** [comment]
I think it can be merged into master

**Pull request merged**
