### PR TITLE
fix: ignore MacOS tmp files

### PR DESCRIPTION
**Pull request by ffsinger**
#461 

Tell me if you know other files that should be ignored

### CODE REVIEW

**Review by fquellec — APPROVED** [review]
That's all I think

**Comment by streitlua** [comment]
In the Uber data, there is a file `.DS_Store` so maybe we should do a regex match that is case unsensitive?

**Comment by ffsinger** [comment]
Good point, it's fixed

**Review by streitlua — APPROVED** [review]
Looks good to me!

**Pull request merged**
