### PR TITLE
fix: auto-run subexperiences

### PR DESCRIPTION
**Pull request by valentinoli**
Addresses #365

### CODE REVIEW

**Comment by valentinoli** [comment]
I'd like to suggest after this PR has been reviewed and merged that we move `UnitSql.vue` into the `unit` folder and rename pipeline components like so:

`UnitSql.vue` -> `UnitPipelineSql.vue`
`UnitSparql.vue` -> `UnitPipelineSparql.vue`
`UnitCustomPipeline.vue` -> `UnitPipelineCustom.vue`

and then move them to folder `unit/pipeline/`

**Review by ffsinger — APPROVED** [review]
Nice, good job !

I noticed that the overlay does not show up for SQL pipelines, but it might be because we are not using web workers for them yet ?

**Comment by valentinoli** [comment]
> I noticed that the overlay does not show up for SQL pipelines, but it might be because we are not using web workers for them yet ?

It has nothing to do with web workers. The overlay only shows if the computation takes long time. If it is short, then no overlay shows - otherwise the overlay would flash in an annoying way.

Currently, I think this is our best solution. Terminating web workers can be a later solution if we want.

**Comment by ffsinger** [comment]
> The overlay only shows if the computation takes long time

But if you try the twitter targeting criteria experience with the big dataset, it does take a long time and doesn't show the overlay.

**Comment by valentinoli** [comment]
> But if you try the twitter targeting criteria experience with the big dataset, it does take a long time and doesn't show the overlay.

Yes, I noticed and I don't know why. I think it happens in Chrome and not on Firefox for example. Generally, I have noticed that the UI lags more in Chrome than it does in Firefox for some reason. So I think what you described might be related to that. Otherwise, it might be something else I overlooked

**Comment by andreaskundig** [comment]
This breaks #400. When you change the options of a pipeline, you can no longer execute them :(

**Comment by andreaskundig** [comment]
I reverted the merge

**Pull request merged**
