### PR TITLE
feat: add filters for time series graph

### PR DESCRIPTION
**Pull request by fquellec**
This PR is related to #354 and fix the following: 
- ability to fill missing values with 0
- ability to add filters for time series (see screenshots)
- minor tweaks for Netflix experience
- adapt format expected by the graph from wide to long (needed to adjust tinder experience too)

image
image

### CODE REVIEW

**Comment by streitlua** [comment]
There are conflicts to be solved after the merge of #436.
I don't have netflix data to test this, I'll try to get some soon

**Review by streitlua — COMMENTED** [review]
The graphs look very nice, I just have some problems with the Settings/Filter in Netflix/Notifications: 
- I would replace `Interacted with`: `0/1` with `no/yes` for clarity
- In `Device model`, it's unclear what the options `--` and `  ` represent

Also, I can't find the ability to fill missing values by 0.

**Comment by fquellec** [comment]
fixed an issue with filling in missing values, date ranges were not inclusive, for other remarks, as discussed with @streitlua, this may be necessary later but for now we need to merge this PR quickly.

**Review by streitlua — APPROVED** [review]
Looks good to me!
As we discussed, when the filter removes all data points, an empty graph appears
image
This could be improved, but this can be done in another PR :)

**Pull request merged**
