### PR TITLE
feat: Web Share (#286)

### PR DESCRIPTION
**Pull request by valentinoli**
Implemented a share button that uses the Web Share API with a [polyfill](https://github.com/on2-dev/share-api-polyfill/). 

[See issue](https://github.com/hestiaAI/hestialabs-experiences/issues/286)

I've implemented a `BaseShareButton` component. It can be used for file sharing too when the device/browser supports it. I added the share button to `UnitFilterableTable` to share the exported CSV of a data table, and to `UnitVegaViz` to share the viz as an image. The share button in the top right corner of an experience is just for sharing meta-info about the experience page - `url`, `title`, `text`. I append the `hashtags` to the `text`. These properties are also included when a file is shared but can be overwritten.

The Windows native share dialog is quite limiting. I know that the Twitter Windows app supports it (although CSV sharing does not seem to work). For Windows we might want to consider turning it off and [using the polyfill instead](https://github.com/on2-dev/share-api-polyfill/issues/69#issuecomment-863512457) but this we can discuss.

**Polyfill**
Note that the [polyfill](https://github.com/on2-dev/share-api-polyfill/) package does not support file sharing and has some bugs (I have submitted PRs for some) but it is pretty nice! 
My PRs:
https://github.com/on2-dev/share-api-polyfill/pulls/valentinoli

### CODE REVIEW

**Comment by valentinoli** [comment]
might want to use this https://github.com/1904labs/dom-to-image-more

for the ChartView component to produce a single image

instead of extracting all the d3 vizualization SVG elements in the ChartView and creating an image for each one

**Review by ffsinger — CHANGES_REQUESTED** [review]
You have updated all the dependencies in `package-lock.json` (e.g. webpack has been updated to version 5). 

I made the same mistake a few days ago in https://github.com/hestiaAI/hestialabs-experiences/pull/328, and fixed in https://github.com/hestiaAI/hestialabs-experiences/commit/e6adc803a1b9fec1a2dd5e0dd46487861842b94b

Otherwise, code looks good

**Comment by valentinoli** [comment]
> You have updated all the dependencies in `package-lock.json` (e.g. webpack has been updated to version 5). 
> 
> I made the same mistake a few days ago in https://github.com/hestiaAI/hestialabs-experiences/pull/328, and fixed in https://github.com/hestiaAI/hestialabs-experiences/commit/e6adc803a1b9fec1a2dd5e0dd46487861842b94b
> 
> Otherwise, code looks good

Oh no! I had some issues with that... thanks for noticing.

**Comment by ffsinger** [comment]
The button at the top right works fine for me, but the other "Share" buttons in the viz/tables are not visible on my machine (Linux, Firefox or Chromium), even though they are listed in the component hierarchy of vue-dev-utils. Do you have an idea of what could be the problem?

**Comment by valentinoli** [comment]
You are right Florian that if there is no share button the export button is not needed but I found it clumsy and even more inconsistent to remove it... Also, the code becomes cleaner and the old workaround for the export+download in 1 click of the download button is not needed...

Downside is that the user needs to first export and then download...

**Comment by ffsinger** [comment]
I agree that for the table it's fine to have the Export and Download as separate buttons if the share option is not possible. But for the visualizations it's confusing to have this export button that does nothing, e.g. for the twitter advertising overview it's like this:

Screenshot_20211220_112928

**Comment by valentinoli** [comment]
Ok, that is not good

I have to take a better look

**Comment by valentinoli** [comment]
@ffsinger 
Now the Export button should never appear on its own. I forgot to add a Download button beside it.
By the way, I created a component `ChartViewVRowWebShare` that is basically a `VRow` with the export/download/sharing functionality. Clicking "Export" is exporting the entire content of the `VRow` as an image.

**Review by ffsinger — COMMENTED** [review]
`ChartViewSunburst` should also use `ChartViewVRowWebShare`

Otherwise it looks good now

**Review by ffsinger — APPROVED** [review]

**Comment by valentinoli** [comment]
@andreaskundig your review is pending

**Comment by andreaskundig** [comment]
@valentinoli I took this week off, but one approval is enough for a pull request, you can merge it.

**Pull request merged**
