### PR TITLE
feat: consent form upgrade

### PR DESCRIPTION
**Pull request by ffsinger**
Added support for text input fields in the consent form. Also removed `saveFiles` parameter that is no longer usable since the `fileManager` refactoring.

### CODE REVIEW

**Comment by ffsinger** [comment]
Address part of #237

**Review by streitlua — APPROVED** [review]
Looks good, seems to be working for me!

I suggest adding a consent section to one of the configs as an example.
Also, what is the deal with the `readonly` prop? It is never given so it defaults to false all the time.

**Comment by ffsinger** [comment]
> I suggest adding an input consent section to one of the configs as an example.

It has been added as an example to `config/config.json`, and it's documented in the readme.

> what is the deal with the readonly prop? It is never given so it defaults to false all the time.

It is used in `pages/import.vue`, line 64. When we import a zip, the consent form is read-only

**Comment by streitlua** [comment]
My bad, it's all good to me then!

**Pull request merged**
