### PR TITLE
Bubble authentication (client)

### PR DESCRIPTION
**Pull request by valentinoli**
#708

### CODE REVIEW

**Comment by valentinoli** [comment]
One thing that is missing and I did not implement is to keep track of the user so that he is still logged in when the page is refreshed or if he leaves the session and comes back later. I think it requires a token...

**Review by fquellec — APPROVED** [review]
Very nice work! 
I notice a small problem when you are logged in a bubble, if you try to go to another bubble, it takes 2 clicks on the same button to get there (the first one doesn't seems to do anything). A suggestion that could also solve this problem would be to disconnect the user each time he leaves the bubble, to go to the home directory or to other pages, it is indeed a bit weird to be connected to something on the main page without knowing what. 
I will merge the PR  we can discuss this later !

**Comment by valentinoli** [comment]
> the first one doesn't seems to do anything

the first click detects the user is trying to access another bubble, so the user is logged out and auto-redirected to the home page

**Comment by valentinoli** [comment]
> to go to the home directory or to other pages, it is indeed a bit weird to be connected to something on the main page without knowing what

I do not think it is weird, it is a very common pattern

**Pull request merged**
