### PR TITLE
fix: #375 format field to dates when header contains "date" or "time" substrings

### PR DESCRIPTION
**Pull request by fquellec**

### CODE REVIEW

**Review by ffsinger — CHANGES_REQUESTED** [review]
I tried with the facebook file `your_off-facebook_activity.json` (experience "Ad interactions") and it doesn't work as expected. The timestamp in the file is given as a standard Unix timestamp (number of seconds passed from 1970). But a Javascript Date expects a timestamp representing the number of _milliseconds_ passed from 1970 ([see here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#the_ecmascript_epoch_and_timestamps)). So you should multiply `value` by 1000 **if** it looks like a unix timestamp

**Comment by fquellec** [comment]
Yes, as we discussed this morning, this is a quick workaround needed for tomorrow's deep-dive. Many date formats are possible and we could detect them as we do with the generic date viewer, but I think doing this every time we post a table could slow the process down unnecessarily. For example how do you detect timestamps in milliseconds or seconds (both are possible) and without detecting phone numbers ?

**Comment by ffsinger** [comment]
I'd say that the timestamp in milliseconds is much less likely than in seconds, because the former seems to be only used in javascript.

If it's really needed for tomorrow we can merge it like this, but it's really confusing to have all these dates show up as 1970 in the Facebook experience

**Comment by fquellec** [comment]
um in my experience I seem to encounter more timestamps in milliseconds than in seconds but you're right it's weird to have all these dates displayed as 1970, let's discuss this during tomorrow's meeting!

**Review by andreaskundig — APPROVED** [review]

**Review by ffsinger — APPROVED** [review]

**Pull request merged**
