### PR TITLE
fix: xlsx crash

### PR DESCRIPTION
**Pull request by ffsinger**
The latest refactoring on `UnitFilterableTable` broke the XLSX viewer

Related to #411

### CODE REVIEW

**Review by andreaskundig — COMMENTED** [review]
After having merged this because it's good that it fixes the xslx viewer, I wonder:  shouldn't formatObject return a string? If the xlsx viewer displays just converts this to a string "null", we should be doing it here explicitly, for example with  `''+object `

**Comment by ffsinger** [comment]
Hmm if we want the UnitFilterableTable to show a blank space on null values, we need to pass either null or an empty string. If it becomes the string "null" it will show up in the table and we don't want that.

So if we really want the format function to return a string, it should be the empty string. Should I make this change ?

**Comment by andreaskundig** [comment]
Ok for the empty string

**Comment by ffsinger** [comment]
Fixed in 4c0b1a75c5073e6756319de64d79574ad1cf3d6e

**Pull request merged**
